# Generated by Django 2.0.13 on 2019-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageChoice', models.PositiveIntegerField(blank=True, choices=[(1, 'JAVA'), (2, 'C++'), (3, 'C'), (4, 'PYTHON 3.6')], null=True)),
                ('problemMandatoryData', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='savedCodeData',
            fields=[
                ('codeId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('problemData', models.FileField(blank=True, upload_to='portal/savedCodes')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('lastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='savedNoteData',
            fields=[
                ('noteId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('noteData', models.FileField(blank=True, upload_to='portal/savedNotes')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('lastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('problemData', models.FileField(blank=True, upload_to='portal')),
                ('submissionId', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
