# Generated by Django 2.0.13 on 2019-05-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondata',
            name='inputFile',
            field=models.FileField(blank=True, null=True, upload_to='portal/runCode'),
        ),
        migrations.AlterField(
            model_name='submissiondata',
            name='problemData',
            field=models.FileField(blank=True, upload_to='portal/runCode'),
        ),
    ]
