# Generated by Django 2.0.13 on 2019-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190510_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondata',
            name='outputFile',
            field=models.FileField(blank=True, null=True, upload_to='portal/runCode'),
        ),
    ]
